#include <iostream>

void CountNucleotides(std::string sequence) {

    int A = 0;
    int G = 0;
    int C = 0;
    int T = 0;

    for (int i = 0; i < sequence.length(); i++) {
        if (sequence[i] == *"A") {
            A++;
        }
        else if (sequence[i] == *"G") {
            G++;
        }
        else if (sequence[i] == *"C") {
            C++;
        }
        else {
            T++;
        }

    }


    std::cout << A << " " << C << " " << G << " " << T;

};


int main()
{

    std::string seq = "ACATGAAAGCAACTAACGCACCGTAAGGTAGTGTAGAGGAATGGGTATTACTTATGCATGGGACCTCCCAGACGTGACTGTGCAATAGCGCGGGCGAGGAGGAACAACTATAATCCTGAGCGGCGATCATGCTAATCACGCGCTGACGAGAGGCCCTCTAGCCATGCCTTGAAGGTTTGGGTTATCGCCAGGGGAAAACTGGTTTTTATCCTCACTACATAGTCTCTAATTCTCAGTTGTATTTCCGTTCGATCAGCCCTGCTTCACTGTTAAGATGGTACTTCTAGATGCAAGGTTGATATATGTGTCGGGGCGAAAATAGCTCTCATAATCCTCCTTCTGTTGCAGGGGGCAATACCCAAATTGAATCAGCATGCCCCAAACCCGATCGCCATGCGCGCAGGTCAACTCGTTCTGAGCAATACGTGGGACGTATGTGGAACAATTACACAGCGTAGGCCAAAGACTTGCCAAGCAACAGTGGCGAGAATCTAGTACATCGTTCGTATTGGTCTCTTGCTAGGTGTTAATCCTTTCAGTATGTAGGTTACCTACGCCCAATAGGGTCGGATCCCGTTGTAACTCGTCAACATAATACGGTGACTGATCCTGGCCCTCTGGCAAGACCAGTGCAGGGGAACTAGCGAGTCATGCTTGGCCCTTTCGAACCGGGACGTTATCAATGCACGCTCTAGAAAACGGACATTACCATTAGCATGCTCTTCCTACGTCGAATCAAGTTGGGAGCTAAGAGGTATGCTTCCTGGATCGTTCGCAAACATGCGTATTCGAGATACATGCCCCTTTTTTCGACCTGGACCGAGGTCAAACTAAGGCATATTGTCCCACGTCCTGAGCTATTACCCGCCTGTTGAGACAAGAAGCGCGAACACCT";

   
    CountNucleotides(seq);

}