#include <iostream>

void CountNucleotides(std::string sequence) {

    int A = 0;
    int G = 0;
    int C = 0;
    int T = 0;

    for (int i = 0; i < sequence.length(); i++) {
        if (sequence[i] == *"A") {
            A++;
        }
        else if (sequence[i] == *"G") {
            G++;
        }
        else if (sequence[i] == *"C") {
            C++;
        }
        else {
            T++;
        }

    }


    std::cout << "A: " << A << "\n";
    std::cout << "C: " << C << "\n";
    std::cout << "G: " << G << "\n";
    std::cout << "T: " << T << "\n";
};


int main()
{

    std::string seq = "TGGAAGCTCAGCGCTTACGCAACTTGTTGGTAACAGATTGATTCTCCAACTGGTGTCGGGAACCATGACTTGCATCCGGCACACGGTCGTCAAGACCGCATTGATGCCTTAATCTGAGAAAGGAATGCTCCGACCCCCTTCAGTGCTGTTGTGCCGATGAAGATACCAGCCTTTCGCGGCGTGCAATCCCGACCTGAAATATTCGGTGGCGGGCGAATAGCACAAAGTTGAGCAGAACGTCCGTATGGCCGCGGAACACGAGGCGCCCGGTGCTACATATCATGGACGCAACTATTAACGGCTCTTGTCTCAAATTACCGGCGCAGATGTCGGGGGCGACGCAGGACGTCACGTATCGTCCGCCGCGTCACTGGTGGAACGGGAGTAGGATTTGTAAGCCAGCGCCAAGAAGAGGGCCTCATGTTTCGTTGGCCGGCTAGTGACTCCAAAGCGCTCTTAGCGCCGTCATCGCCTTGATGAAGAGCAGAACTCCTCGGATTTCTAGCCGACAGAGGCATTGGTACACAAGGATCCAAGTGGGAGCGTACTTACAGAGTTCCTCCCGGCACCATTCCCGGTAAAAAAGCAACGGTGCCATTACGGTCTTTCTAAATAACCCAGTGGAACAACTGCACACTGTCCGATTACTATAGTTGGCTAGGACGCCGCCGCTATTGTCCAGTTCGCCAATCCAACGACAGTCCTGCCTCACTGATCAACGCTTATTTACTATGATCGCAACTGATTCATAGGAATGTCCTAATCGTGGGATTTCTTGGAAAATTGACGGGAAAGACGTACTCCAAGTACTCAAATCTTCCCACGACTTCACTGTAAAATAATCGC";

   
    CountNucleotides(seq);

}